import * as Location from 'expo-location';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { SymbolView } from 'expo-symbols';
import { useEffect, useRef, useState } from 'react';
import { Keyboard, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { LocationPickerMap } from '@/components/location-picker-map';
import { BackButton, Button, Notice, Screen } from '@/components/ui';
import { Colors, Elevation, Radius, Spacing, Typography } from '@/constants/colors';
import { coordinateFromLocation, requestCurrentLocation, reverseGeocodeLabel, type Coordinate } from '@/lib/location';
import { type LocationPurpose, useLocationPickerStore } from '@/stores/location-picker-store';
const TITLES: Record<LocationPurpose, string> = { 'ride-pickup': 'Lokasi jemput', 'ride-destination': 'Tujuan perjalanan', 'send-pickup': 'Lokasi pengambilan', 'send-destination': 'Tujuan pengiriman', 'food-destination': 'Alamat pengantaran' };
export default function LocationPickerScreen() {
 const router = useRouter(); const params = useLocalSearchParams<{ purpose?: string }>(); const purpose = (params.purpose ?? 'ride-pickup') as LocationPurpose; const previous = useLocationPickerStore((s) => s.selections[purpose]); const setSelection = useLocationPickerStore((s) => s.setSelection);
 const [coordinate, setCoordinate] = useState<Coordinate | undefined>(previous?.coordinate); const [address, setAddress] = useState(previous?.address ?? 'Geser peta atau gunakan lokasi saat ini'); const [query, setQuery] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
 const updateAddress = async (point: Coordinate) => { setBusy(true); setAddress(await reverseGeocodeLabel(point)); setBusy(false); };
 const mapChanged = (point: Coordinate) => { setCoordinate(point); setAddress('Mencari alamat…'); if (timer.current) clearTimeout(timer.current); timer.current = setTimeout(() => { void updateAddress(point); }, 550); };
 useEffect(() => () => { if (timer.current) clearTimeout(timer.current); }, []);
 const handleGps = async () => { try { setError(''); setBusy(true); const point = coordinateFromLocation(await requestCurrentLocation()); setCoordinate(point); await updateAddress(point); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Lokasi tidak tersedia.'); setBusy(false); } };
 const search = async () => { if (!query.trim()) return; try { Keyboard.dismiss(); setError(''); setBusy(true); const results = await Location.geocodeAsync(query.trim()); if (!results.length) { setError('Lokasi tidak ditemukan. Coba nama tempat atau alamat yang lebih lengkap.'); return; } const point = { latitude: results[0].latitude, longitude: results[0].longitude }; setCoordinate(point); await updateAddress(point); } catch { setError('Pencarian lokasi belum tersedia. Coba gunakan GPS atau geser peta.'); } finally { setBusy(false); } };
 const confirm = () => { if (!coordinate) { setError('Pilih lokasi terlebih dahulu.'); return; } setSelection(purpose, { coordinate, address }); router.back(); };
 return <Screen scroll={false} contentStyle={styles.screen}><View style={styles.header}><BackButton onPress={() => router.back()} /><Text style={styles.title}>{TITLES[purpose]}</Text><View style={styles.headerSpace} /></View><View style={styles.search}><SymbolView name={{ ios: 'magnifyingglass', android: 'search', web: 'search' }} size={20} tintColor={Colors.muted} /><TextInput value={query} onChangeText={setQuery} onSubmitEditing={() => void search()} returnKeyType="search" placeholder="Cari tempat atau alamat" placeholderTextColor={Colors.subtle} style={styles.searchInput} /><Pressable onPress={() => void search()}><Text style={styles.searchAction}>Cari</Text></Pressable></View><View style={styles.mapWrap}><LocationPickerMap coordinate={coordinate} onChange={mapChanged} /><Pressable accessibilityRole="button" accessibilityLabel="Gunakan lokasi saya" onPress={() => void handleGps()} style={styles.gps}><SymbolView name={{ ios: 'location.fill', android: 'my_location', web: 'my_location' }} size={23} tintColor={Colors.primary} /></Pressable></View><View style={styles.bottom}><View style={styles.addressRow}><View style={styles.addressIcon}><SymbolView name={{ ios: 'mappin', android: 'location_on', web: 'location_on' }} size={20} tintColor={Colors.primary} /></View><View style={styles.addressCopy}><Text style={styles.addressLabel}>LOKASI TERPILIH</Text><Text numberOfLines={2} style={styles.address}>{busy ? 'Mencari alamat…' : address}</Text></View></View>{error ? <Notice tone="danger">{error}</Notice> : null}<Button title="Pilih lokasi" loading={busy} disabled={!coordinate} onPress={confirm} /></View></Screen>;
}
const styles = StyleSheet.create({ screen: { paddingTop: Spacing.sm, paddingHorizontal: Spacing.md, gap: Spacing.md }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { color: Colors.text, ...Typography.sectionTitle }, headerSpace: { width: 42 }, search: { minHeight: 52, flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, paddingHorizontal: Spacing.md, borderRadius: Radius.lg, backgroundColor: Colors.surface, borderWidth: 1, borderColor: Colors.border, ...Elevation.card }, searchInput: { flex: 1, color: Colors.text, fontSize: 16 }, searchAction: { color: Colors.primaryDark, ...Typography.caption }, mapWrap: { flex: 1 }, gps: { position: 'absolute', right: Spacing.md, bottom: Spacing.md, width: 50, height: 50, borderRadius: 25, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.surface, ...Elevation.floating }, bottom: { gap: Spacing.md, paddingBottom: Spacing.md }, addressRow: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: Spacing.md }, addressIcon: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.primarySoft }, addressCopy: { flex: 1, gap: 3 }, addressLabel: { color: Colors.muted, fontSize: 10, fontWeight: '800', letterSpacing: .6 }, address: { color: Colors.text, ...Typography.body, fontWeight: '700' } });

