import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import { SymbolView } from 'expo-symbols';
import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { BackButton, StatusState } from './ui';
import { Colors, Radius, Spacing, Typography } from '@/constants/colors';
import { listChatMessages, sendChatMessage } from '@/lib/api/chat';
import { getApiErrorMessage } from '@/lib/api/client';
import { chatKeys } from '@/lib/chat-query-keys';
import { formatDateTime } from '@/lib/format';
import { useAuthStore } from '@/stores/auth-store';
export function ChatThreadScreen({ orderId }: { orderId: number }) {
 const router = useRouter(); const client = useQueryClient(); const userId = useAuthStore((s) => s.user?.id); const [body, setBody] = useState('');
 const query = useQuery({ queryKey: chatKeys.thread(orderId), queryFn: () => listChatMessages(orderId), enabled: Number.isFinite(orderId), refetchInterval: 3_000 });
 const mutation = useMutation({ mutationFn: (message: string) => sendChatMessage(orderId, message), onSuccess: async () => { setBody(''); await Promise.all([client.invalidateQueries({ queryKey: chatKeys.thread(orderId) }), client.invalidateQueries({ queryKey: chatKeys.all })]); } });
 const submit = () => { const message = body.trim(); if (message && !mutation.isPending) mutation.mutate(message); };
 return <SafeAreaView style={styles.safe} edges={['top','left','right','bottom']}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.header}><BackButton onPress={() => router.back()} /><View style={styles.headerCopy}><Text style={styles.title}>Chat pesanan</Text><Text style={styles.subtitle}>Pesan #{orderId}</Text></View></View>{query.isLoading ? <StatusState type="loading" /> : query.isError ? <StatusState type="error" message={getApiErrorMessage(query.error)} /> : <ScrollView style={styles.messages} contentContainerStyle={styles.messagesContent} keyboardShouldPersistTaps="handled">{!query.data?.length ? <View style={styles.start}><SymbolView name={{ ios: 'bubble.left.fill', android: 'chat_bubble', web: 'chat_bubble' }} size={26} tintColor={Colors.primary} /><Text style={styles.startTitle}>Mulai percakapan</Text><Text style={styles.startCopy}>Gunakan chat untuk informasi terkait pickup dan pengantaran.</Text></View> : query.data.map((message) => { const mine = message.sender_id === userId; return <View key={message.id} style={[styles.messageRow, mine && styles.messageRowMine]}><View style={[styles.bubble, mine && styles.bubbleMine]}><Text style={[styles.message, mine && styles.messageMine]}>{message.body}</Text><Text style={[styles.timestamp, mine && styles.timestampMine]}>{formatDateTime(message.created_at)}</Text></View></View>; })}</ScrollView>} {mutation.isError ? <Text style={styles.error}>{getApiErrorMessage(mutation.error)}</Text> : null}<View style={styles.composer}><TextInput value={body} onChangeText={setBody} placeholder="Tulis pesan…" placeholderTextColor={Colors.subtle} multiline maxLength={2000} style={styles.input} /><Pressable accessibilityRole="button" accessibilityLabel="Kirim pesan" disabled={!body.trim() || mutation.isPending} onPress={submit} style={[styles.send, (!body.trim() || mutation.isPending) && styles.disabled]}><SymbolView name={{ ios: 'paperplane.fill', android: 'send', web: 'send' }} size={21} tintColor={Colors.white} /></Pressable></View></KeyboardAvoidingView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.background }, flex: { flex: 1 }, header: { minHeight: 66, flexDirection: 'row', alignItems: 'center', gap: Spacing.md, paddingHorizontal: Spacing.lg, borderBottomWidth: 1, borderBottomColor: Colors.border, backgroundColor: Colors.surface }, headerCopy: { gap: 1 }, title: { color: Colors.text, ...Typography.cardTitle }, subtitle: { color: Colors.muted, ...Typography.caption }, messages: { flex: 1 }, messagesContent: { flexGrow: 1, justifyContent: 'flex-end', gap: Spacing.sm, padding: Spacing.lg }, messageRow: { alignItems: 'flex-start' }, messageRowMine: { alignItems: 'flex-end' }, bubble: { maxWidth: '82%', gap: 4, paddingHorizontal: 14, paddingVertical: 10, borderRadius: Radius.lg, backgroundColor: Colors.surface, borderWidth: 1, borderColor: Colors.border }, bubbleMine: { backgroundColor: Colors.primary, borderColor: Colors.primary }, message: { color: Colors.text, ...Typography.body }, messageMine: { color: Colors.white }, timestamp: { color: Colors.subtle, fontSize: 10 }, timestampMine: { color: '#D1FAE5' }, start: { alignItems: 'center', gap: Spacing.sm, padding: Spacing.xxxl }, startTitle: { color: Colors.text, ...Typography.cardTitle }, startCopy: { color: Colors.muted, ...Typography.metadata, textAlign: 'center' }, composer: { flexDirection: 'row', alignItems: 'flex-end', gap: Spacing.sm, padding: Spacing.md, borderTopWidth: 1, borderTopColor: Colors.border, backgroundColor: Colors.surface }, input: { flex: 1, maxHeight: 110, minHeight: 46, color: Colors.text, fontSize: 16, paddingHorizontal: 15, paddingVertical: 11, borderRadius: 23, backgroundColor: Colors.surfaceMuted }, send: { width: 46, height: 46, borderRadius: 23, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.primary }, disabled: { opacity: .45 }, error: { color: Colors.danger, ...Typography.caption, paddingHorizontal: Spacing.lg, paddingVertical: Spacing.xs } });
