import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { isAxiosError } from 'axios';
import { useRouter } from 'expo-router';
import { Controller, useForm } from 'react-hook-form';
import { useEffect } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { LocationField } from '@/components/location-field';
import { BackButton, Button, Card, FormField, Notice, PageHeader, Screen, SectionHeader } from '@/components/ui';
import { Colors, Spacing, Typography } from '@/constants/colors';
import { getApiErrorMessage } from '@/lib/api/client';
import { createSend } from '@/lib/api/send';
import { orderKeys } from '@/lib/query-keys';
import { createSendSchema, type CreateSendForm } from '@/schemas/send';
import { useLocationPickerStore } from '@/stores/location-picker-store';
import type { ApiErrorPayload } from '@/types/api';
const defaults: CreateSendForm = { pickup_address: '', pickup_latitude: '', pickup_longitude: '', destination_address: '', destination_latitude: '', destination_longitude: '', item_name: '', item_description: '', recipient_name: '', recipient_phone: '', notes: '' };
export default function CreateSendScreen() {
 const router = useRouter(); const client = useQueryClient(); const pickup = useLocationPickerStore((s) => s.selections['send-pickup']); const destination = useLocationPickerStore((s) => s.selections['send-destination']);
 const { control, handleSubmit, setError, setValue, formState: { errors } } = useForm<CreateSendForm>({ resolver: zodResolver(createSendSchema), defaultValues: defaults });
 useEffect(() => { if (pickup) { setValue('pickup_address', pickup.address, { shouldValidate: true }); setValue('pickup_latitude', String(pickup.coordinate.latitude), { shouldValidate: true }); setValue('pickup_longitude', String(pickup.coordinate.longitude), { shouldValidate: true }); } }, [pickup, setValue]);
 useEffect(() => { if (destination) { setValue('destination_address', destination.address, { shouldValidate: true }); setValue('destination_latitude', String(destination.coordinate.latitude), { shouldValidate: true }); setValue('destination_longitude', String(destination.coordinate.longitude), { shouldValidate: true }); } }, [destination, setValue]);
 const mutation = useMutation({ mutationFn: createSend, onSuccess: async ({ order }) => { await client.invalidateQueries({ queryKey: orderKeys.all }); router.replace({ pathname: '/(customer)/send/[id]', params: { id: String(order.id) } }); } });
 const submit = handleSubmit((value) => mutation.mutate({ pickup_address: value.pickup_address.trim(), pickup_latitude: Number(value.pickup_latitude), pickup_longitude: Number(value.pickup_longitude), destination_address: value.destination_address.trim(), destination_latitude: Number(value.destination_latitude), destination_longitude: Number(value.destination_longitude), item_name: value.item_name.trim(), item_description: value.item_description?.trim() || null, recipient_name: value.recipient_name.trim(), recipient_phone: value.recipient_phone.trim(), notes: value.notes?.trim() || null, payment_method: 'cash' }, { onError: (error) => { if (!isAxiosError<ApiErrorPayload>(error)) return; Object.entries(error.response?.data?.errors ?? {}).forEach(([field, messages]) => { if (field in defaults) setError(field as keyof CreateSendForm, { type: 'server', message: messages[0] }); }); } }));
 const openPicker = (purpose: 'send-pickup' | 'send-destination') => router.push({ pathname: '/(customer)/location-picker', params: { purpose } }); const locationError = errors.pickup_address?.message || errors.pickup_latitude?.message || errors.destination_address?.message || errors.destination_latitude?.message;
 return <Screen><PageHeader eyebrow="SEND" title="Kirim barang" description="Isi tujuan dan data penerima dalam satu langkah." action={<BackButton onPress={() => router.back()} />} /><Card><LocationField label="Dari mana?" value={pickup?.address} placeholder="Pilih lokasi pengambilan" onPress={() => openPicker('send-pickup')} /><LocationField label="Kirim ke mana?" value={destination?.address} placeholder="Pilih lokasi penerima" onPress={() => openPicker('send-destination')} /></Card>{locationError ? <Notice tone="danger">{locationError}</Notice> : null}<View style={styles.section}><SectionHeader title="Barang" /><Controller control={control} name="item_name" render={({ field }) => <FormField label="Nama barang" placeholder="Contoh: Dokumen" returnKeyType="next" value={field.value} onChangeText={field.onChange} error={errors.item_name?.message} />} /><Controller control={control} name="item_description" render={({ field }) => <FormField label="Detail barang (opsional)" placeholder="Ukuran, warna, atau ciri barang" value={field.value} onChangeText={field.onChange} error={errors.item_description?.message} />} /></View><View style={styles.section}><SectionHeader title="Penerima" /><Controller control={control} name="recipient_name" render={({ field }) => <FormField label="Nama penerima" returnKeyType="next" value={field.value} onChangeText={field.onChange} error={errors.recipient_name?.message} />} /><Controller control={control} name="recipient_phone" render={({ field }) => <FormField label="Nomor HP penerima" keyboardType="phone-pad" returnKeyType="done" value={field.value} onChangeText={field.onChange} error={errors.recipient_phone?.message} />} /><Controller control={control} name="notes" render={({ field }) => <FormField label="Catatan untuk driver (opsional)" multiline numberOfLines={3} value={field.value} onChangeText={field.onChange} error={errors.notes?.message} />} /></View>{mutation.isError ? <Notice tone="danger">{getApiErrorMessage(mutation.error)}</Notice> : null}<Text style={styles.helper}>Biaya pengiriman dihitung otomatis berdasarkan jarak.</Text><Button title="Cari Driver" loading={mutation.isPending} onPress={submit} /></Screen>;
}
const styles = StyleSheet.create({ section: { gap: Spacing.md }, helper: { color: Colors.muted, ...Typography.metadata, textAlign: 'center', paddingTop: Spacing.md } });
